### ISSUE TITLE
[Endpuntk] Benachrichtigen

### ISSUE THREAD

**Issue by FabianWilms** [WeisswurstSystems/WWM-BB#16]
Endpunkt `/{meetingId}/do/notify`.

Bei post mit `message` und `title` als Body werden alle Teilnehmer des Meetings per Mail informiert über den mitgelieferten Text.

**Comment by peter-mueller** [comment]
machst du das, wenn du invite auch schon gemacht hast?

**Comment by FabianWilms** [comment]
sischer dat!
