### ISSUE TITLE
Change mux-Router zu macaron

### ISSUE THREAD

**Issue by FabianWilms** [WeisswurstSystems/WWM-BB#19]
https://github.com/go-macaron/macaron

**Comment by FabianWilms** [comment]
Nach ausprobieren: Funktioniert leider nicht so einfach wie es sollte...die Doku ist noch etwas zu schwammig.

**Comment by FabianWilms** [comment]
vll. ist noch nicht alle Hoffnung verloren...
Zum Einsatz muss allerdings das hier geklärt werden https://github.com/go-macaron/macaron/issues/134

**Comment by darenegade** [comment]
Mal über ein anderes Webframework nachgedacht? Die Funktion, die du dir von macaron wünschst, können andere schon.
Z.B. Iris, Martini, ....

**Comment by FabianWilms** [comment]
@darenegade Danke für die Hinweise. Iris ist aber mehr für Website serving und Martini nicht weiterentwickelt...

Hat sich durch die neue Architektur sowie erledigt und wird nicht mehr benötigt. Und mittlerweile hat man mir sogar auf das Macaron Issue geantwortet und es wäre auch damit einiges möglich gewesen.
