### ISSUE TITLE
Mail-Bestätigung bei Registrierung

### ISSUE THREAD

**Issue by FabianWilms** [WeisswurstSystems/WWM-BB#23]
Ablauf:

1. Nutzer registriert sich
1a. User wird in seperater Tabelle gespeichert (z.B. registerUsers) mit unlock-id
1b. User erhält unlock-id Feld. Solange dieses Feld vorhanden ist, ist dieser User "nicht aktiv"
2. Nutzer erhält Mail mit unlock-id. Besucht er diese Seite 
2a. Wird der User auf die reguläre User-Tabelle verschoben
2b. wird das unlock-id Feld geleert.
3. Weiterleitung bei success auf Seite von https://github.com/WeisswurstSystems/WWM-ITM mit Text "lorem ipsum registrierung erfolgreich..."

@peter-mueller Lieber Ablauf (a) oder (b)? 

(a) -> Neue Tabelle. Wenig aufwand. Automatische Leerung von "toten" Nutzern einfach (z.B. Datum der registrierung speichern

(b) -> Prüfung, ob unlock-id leer ist muss erfolgen. Automatische Leerung aufwändiger. Dafür nur eine Tabelle

**Comment by peter-mueller** [comment]
würde die emails nicht prüfen, ansonsten find ich b viel besser

**Comment by FabianWilms** [comment]
es geht auch darum zu verhindern, dass tauasend accounts erstellt werden. und man kann so gleich mal das mail verschicken implementieren :P
