### ISSUE TITLE
Speichermethode fixen

### ISSUE THREAD

**Issue by FabianWilms** [WeisswurstSystems/WWM-BB#37]
## Gewünschtes Verhalten

Beim aktualisieren von Daten wird der alte Datensatz aktualsiert

## Aktuelles Verhalten

Der aktualisierte Datensatz wird dupliziert

## Schritte zum reproduzieren des Problems

  1. Registrieren
  2. Aktivieren
  3. In Datenbank schauen -> Nutzer doppelt vorhanden

## Weitere Infos

Vor deiner Architekturumstellung hatte es sich korrekt verhalten. Jetzt gibt es auch nur noch eine Save-Methode. Bitte fixen.

**Comment by FabianWilms** [comment]
Dies gilt für den user und den meeting-store

**Comment by peter-mueller** [comment]
nur noch ein save ist gewollt, es soll kein update geben
